### ISSUE TITLE
Keybinding on xfce not working

### ISSUE THREAD

**Issue by biographie** [AlexisBRENON/ewmh_m2m#13]
I've tried to bind move-to-monitor --direction NORTH to a shortcut however I'm getting an error saying failed to execute child process (No such file or directory). I've installed using pip. However, when I run the command in the terminal window it indeed does shift the the terminal to the other monitor. Does this not work for other application windows. I'm using Xfce. Apologies if this is a trivial question.

**Comment by AlexisBRENON** [comment]
This is a strange issue.

Moving the terminal window when you run the command inside the terminal is the "normal" behavior. The script moves the currently active window, so if you're typing in a terminal, this terminal is active and will be moved.

However, given the error message returned, I think that XFCE does not find the command. This can happen if some `PATH` values are added in startup files that are not read by the login manager/x server/xfce...

In your terminal run the following command:
```bash
which move-to-monitor
```

Try to use this full absolute path in your XFCE key binding (instead of just `move-to-monitor`).

**Comment by biographie** [comment]
Awesome! Your solution worked. I reckon it's because python3 has been installed via anaconda thus /home/biographie/anaconda3/bin/move-to-monitor

**Comment by nezam05** [comment]
Please consider to add this info in README file.
